name: Deploy to GitHub Pages
uses: JamesIves/github-pages-deploy-action@3.5.2
on:
    push:
        branches:
            - master
jobs:
    build-and-deploy:
        - name: deploy 🥳
          run: yarn deploy
